---

# - name: Ajouter clé PostgreSQL
#   get_url:
#     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
#     dest: /etc/apt/trusted.gpg.d/postgresql.asc

- name: Ajouter le dépôt PostgreSQL
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql
    update_cache: yes

- name: Installation de PostgreSQL
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Activation et démarrage de PostgreSQL
  systemd:
    name: postgresql
    state: started
    enabled: true

- name: Obtenir la version de PostgreSQL
  shell: psql --version | head -n 1 | awk '{print $3}' | awk -F. '{print $1}'
  register: postgresql_version
  changed_when: false
  ignore_errors: true

- name: Configuration de PostgreSQL
  lineinfile:
    regexp: ^#?listen_addresses = .*$
    line: listen_addresses = '*'
    path: /etc/postgresql/{{ postgresql_version.stdout }}/main/postgresql.conf
  notify: Redémarrer PostgreSQL

- name: Configure PostgreSQL authentication for user postgres
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version.stdout }}/main/pg_hba.conf"
    line: "local   all             all                                     md5"
  become: true
  notify: Redémarrer PostgreSQL


# Ayant eu des difficultés pour reussi la creation de l'utilisateur
# j'ai forcé en instalant sudo apt-get install acl sur la machine distant 
# Comme la documentation sur les risques d'utilisateur non privilrgés
- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  become: yes
  become_user: postgres
 