---

mastodon_fqdn: mastotodon.com
mastodon_version: v4.1.0

postgresql_host: "{{ hostvars[groups['mastodon_postgresql'][0]]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
postgresql_user: mastodon
postgresql_password: mastodon
postgresql_database: mastodon_production